/**
 * raymarch_fs330.h — 由 tools/gen_raymarch_glsl330.py 从 gpu_raymarch.c 的 GLSL ES 片元着色器
 * 机械转换而来 (勿手改; 改源着色器后重跑脚本)。供 sokol 后端做真 GPU 光线步进。
 */
#ifndef FXTK_RAYMARCH_FS330_H
#define FXTK_RAYMARCH_FS330_H

static const char *RAYMARCH_FS330 =
    "#version 330\n"
    "/* 由 tools/gen_raymarch_glsl330.py 生成: 原 GLSL ES 片元着色器 + sokol 约定适配 */\n"
    "/* 松散 uniform: sokol(GL) 按名字逐个 glGetUniformLocation 定位, block 成员拿不到 location */\n"
    "uniform vec4 u_rect;\n"
    "uniform float u_time;\n"
    "out vec4 frag_color;\n"
    "\n"
    "\n"
    "\n"
    "float sdTorus(vec3 p){\n"
    "  float ca=cos(u_time*0.6), sa=sin(u_time*0.6);\n"
    "  float x=p.x*ca-p.z*sa; float z=p.x*sa+p.z*ca;\n"
    "  float y2=p.y*0.62-z*0.78; float z2=p.y*0.78+z*0.62;\n"
    "  float q=length(vec2(x,y2))-1.2;\n"
    "  return length(vec2(q,z2))-0.35;\n"
    "}\n"
    "vec3 sphCenter(float t){ return vec3(sin(t*0.9)*1.6, 0.2+0.4*sin(t*1.3), cos(t*0.7)*0.9); }\n"
    "float map(vec3 p){\n"
    "  float d=p.y+1.0;\n"
    "  d=min(d, length(p-sphCenter(u_time))-0.8);\n"
    "  return min(d, sdTorus(p));\n"
    "}\n"
    "vec3 nrm(vec3 p){\n"
    "  vec2 e=vec2(0.002,0.0);\n"
    "  return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),\n"
    "                        map(p+e.yxy)-map(p-e.yxy),\n"
    "                        map(p+e.yyx)-map(p-e.yyx)));\n"
    "}\n"
    "float shadow(vec3 ro, vec3 rd){\n"
    "  float t=0.03;\n"
    "  for(int i=0;i<24;i++){ float h=map(ro+rd*t); if(h<0.002) return 0.3; t+=h; if(t>8.0) break; }\n"
    "  return 1.0;\n"
    "}\n"
    "/* åºæ¯æ±äº¤: è¾åº th(mat), è¿åæè¿ t (0=å¤©ç©º 1=å°é¢ 2=ç 3=åç¯) */\n"
    "float sceneHit(vec3 ro, vec3 rd, float tmax, int steps, out float th, out int mat){\n"
    "  float t=tmax; int m=0;\n"
    "  if(rd.y<-1e-4){ float tp=-(ro.y+1.0)/rd.y; if(tp>0.0 && tp<t){ t=tp; m=1; } }\n"
    "  vec3 sc=sphCenter(u_time);\n"
    "  vec3 oc=ro-sc; float bq=dot(oc,rd); float cq=dot(oc,oc)-0.64; float disc=bq*bq-cq;\n"
    "  if(disc>0.0){ float ts=-bq-sqrt(disc); if(ts>0.01 && ts<t){ t=ts; m=2; } }\n"
    "  float tt=0.02;\n"
    "  for(int i=0;i<steps;i++){ float d=sdTorus(ro+rd*tt);\n"
    "    if(d<0.001){ if(tt<t){ t=tt; m=3; } break; }\n"
    "    tt+=d; if(tt>t || tt>12.0) break; }\n"
    "  th=t; mat=m; return t;\n"
    "}\n"
    "/* åå°å"
    "çº¿çè² (ééå½, ä½æ­¥æ°) */\n"
    "vec3 shadeReflect(vec3 pos, vec3 n, vec3 rd, vec3 L){\n"
    "  vec3 rdir=reflect(rd, n);\n"
    "  float th; int mat;\n"
    "  sceneHit(pos+n*0.01, rdir, 12.0, 24, th, mat);\n"
    "  if(mat==0){\n"
    "    float sk=clamp(0.5+0.5*rdir.y,0.0,1.0);\n"
    "    vec3 c=vec3(0.15+0.35*sk,0.25+0.45*sk,0.45+0.5*sk);\n"
    "    c+=vec3(0.6,0.45,0.2)*pow(max(dot(rdir,L),0.0),4.0);\n"
    "    return c;\n"
    "  }\n"
    "  vec3 p2=pos+n*0.01+rdir*th;\n"
    "  vec3 n2, m2;\n"
    "  if(mat==1){ n2=vec3(0.0,1.0,0.0);\n"
    "    vec2 c=floor(p2.xz*0.8);\n"
    "    m2=(mod(c.x+c.y,2.0)<1.0)?vec3(0.9,0.9,0.95):vec3(0.1,0.15,0.4);\n"
    "  } else if(mat==2){ n2=normalize(p2-sphCenter(u_time)); m2=vec3(1.0,0.45,0.1); }\n"
    "  else { n2=nrm(p2); m2=vec3(0.9,0.2,0.7); }\n"
    "  float d=max(dot(n2,L),0.0);\n"
    "  vec3 c=m2*(0.25+1.4*d);\n"
    "  return mix(vec3(0.2,0.3,0.5), c, exp(-th*0.06));\n"
    "}\n"
    "void main(){\n"
    "  float t=u_time;\n"
    "  vec3 ro=vec3(3.0*cos(t*0.35), 1.2+0.4*sin(t*0.23), 3.0*sin(t*0.35));\n"
    "  vec3 cw=normalize(vec3(0.0,-0.1,0.0)-ro);\n"
    "  vec3 cu=normalize(cross(cw, vec3(0.0,1.0,0.0)));\n"
    "  vec3 cv=cross(cu,cw);\n"
    "  vec2 fl=vec2(gl_FragCoord.x-u_rect.x,(u_rect.y+u_rect.w)-gl_FragCoord.y);\n"
    "  vec2 uv=(2.0*fl-u_rect.zw)/u_rect.zw.y;\n"
    "  vec3 rd=normalize(uv.x*cu+uv.y*cv+1.6*cw);\n"
    "  vec3 L=normalize(vec3(0.6,0.7,-0.35));\n"
    "  float th; int mat;\n"
    "  sceneHit(ro, rd, 1e9, 96, th, mat);\n"
    "  vec3 col;\n"
    "  if(mat==0){\n"
    "    float sk=clamp(0.5+0.5*rd.y,0.0,1.0);\n"
    "    col=vec3(0.15+0.35*sk,0.25+0.45*sk,0.45+0.5*sk);\n"
    "    col+=vec3(0.6,0.45,0.2)*pow(max(dot(rd,L),0.0),4.0);\n"
    "  } else {\n"
    "    vec3 pos=ro+rd*th; vec3 n; vec3 m;\n"
    "    if(mat==1){ n=vec3(0.0,1.0,0.0);\n"
    "      vec2 c=floor(pos.xz*0.8);\n"
    "      m=(mod(c.x+c.y,2.0)<1.0)?vec3(0.9,0.9,0.95):vec3(0.1,0.15,0.4);\n"
    "    } else if(mat==2){ n=normalize(pos-sphCenter(u_time)); m=vec3(1.0,0.45,0.1); }\n"
    "    else { n=nrm(pos); m=vec3(0.9,0.2,0.7); }\n"
    "    float dif=max(dot(n,L),0.0);\n"
    "    float sh=(dif>0.02)?shadow(pos+n*0.02,L):0.0;\n"
    "    float spe=pow(max(dot(n,normalize(L-rd)),0.0),16.0)*sh*1.5;\n"
    "    col=m*(0.25+1.4*dif*sh)+vec3(spe);\n"
    "    col=mix(vec3(0.2,0.3,0.5), col, exp(-th*0.06));\n"
    "    /* éé¢åå°: åç¯0.5 ç0.35 å°é¢0.15 */\n"
    "    float ref=(mat==3)?0.5:((mat==2)?0.35:0.15);\n"
    "    col=mix(col, shadeReflect(pos, n, rd, L), ref);\n"
    "  }\n"
    "  frag_color =vec4(clamp(col,0.0,1.0),1.0);\n"
    "}\n"
;

#endif
